/-
Copyright (c) 2026 Devon Tuma. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Devon Tuma
-/

module

public import Cslib.Foundations.Data.PFunctor.Free.MonadAttach
public import Std.WP.Monad.Basic

/-!
# Weakest preconditions for polynomial free programs

An operation handler into core's `Lean.Order.PredTrans` extends to a `Std.WP.WPMonad`
interpretation by `FreeM.liftM`. Different readings can be installed locally: structural
correctness, expected cost, and probability bounds share the same program syntax.

The constructions are explicit because the choice of operation semantics is not determined
by the polynomial functor. Inspired by `PolyFun.PFunctor.Free.WP.Upstream`.
-/

@[expose] public section

universe uA uB v w z

namespace PFunctor.FreeM

open Lean.Order Std.WP

variable {P : PFunctor.{uA, uB}} {Pred : Type v} {EPred : Type w} {α : Type uB}

/-- Interpreting operations by monotone predicate transformers preserves monotonicity. -/
theorem monotone_liftM [Lean.Order.PartialOrder Pred] [Lean.Order.PartialOrder EPred]
    (interp : (op : P.A) → PredTrans Pred EPred (P.B op))
    (hinterp : ∀ op, (interp op).monotone) (x : P.FreeM α) :
    (x.liftM interp).monotone := by
  induction x with
  | pure a => exact fun _ _ _ _ _ h => h a
  | lift_bind op cont ih =>
    intro post post' epost epost' hepost hpost
    exact hinterp op _ _ _ _ hepost fun b => ih b _ _ _ _ hepost hpost

/-- The core WP interpretation generated by a monotone operation handler. -/
@[instance_reducible]
def wpMonad [Assertion Pred] [Assertion EPred]
    (interp : (op : P.A) → PredTrans Pred EPred (P.B op))
    (hinterp : ∀ op, (interp op).monotone) : WPMonad P.FreeM Pred EPred where
  toWP _ := ⟨FreeM.liftM interp, monotone_liftM interp hinterp⟩
  pure_le_wp_pure _ _ _ := PartialOrder.rel_refl
  bind_le_wp_bind x f post epost := by
    change (x.liftM interp >>= fun a => (f a).liftM interp).apply post epost ⊑ _
    rw [← liftM_bind]
    exact PartialOrder.rel_refl

/-- This interpretation is the ordinary monadic fold into `PredTrans`. -/
theorem wpMonad_wp [Assertion Pred] [Assertion EPred]
    (interp : (op : P.A) → PredTrans Pred EPred (P.B op))
    (hinterp : ∀ op, (interp op).monotone) (x : P.FreeM α)
    (post : α → Pred) (epost : EPred) :
    ((wpMonad interp hinterp).toWP α).wp x post epost =
      (x.liftM interp).apply post epost := rfl

/-- Interpret a free program through a handler into a monad with a core WP interpretation. -/
@[instance_reducible]
def wpMonadOfHandler {m : Type uB → Type z} [Monad m]
    [Assertion Pred] [Assertion EPred] [WPMonad m Pred EPred]
    (interp : (op : P.A) → m (P.B op)) : WPMonad P.FreeM Pred EPred where
  toWP _ :=
    { wpTrans x := WP.wpTrans (x.liftM interp)
      wp_trans_monotone x := WP.wp_trans_monotone (x.liftM interp) }
  pure_le_wp_pure a post epost := WPMonad.pure_le_wp_pure a post epost
  bind_le_wp_bind x f post epost := by
    change wp (x.liftM interp) (fun a => wp ((f a).liftM interp) post epost) epost ⊑
      wp ((x >>= f).liftM interp) post epost
    rw [liftM_bind]
    exact WPMonad.bind_le_wp_bind _ _ _ _

/-- Per-operation lower bounds extend to a lower bound for the interpreted program. -/
theorem liftM_le_wp {m : Type uB → Type z} [Monad m]
    [Assertion Pred] [Assertion EPred] [WPMonad m Pred EPred]
    (spec : (op : P.A) → PredTrans Pred EPred (P.B op))
    (interp : (op : P.A) → m (P.B op))
    (hspec : ∀ op post epost, (spec op).apply post epost ⊑ wp (interp op) post epost)
    (x : P.FreeM α) (post : α → Pred) (epost : EPred) :
    (x.liftM spec).apply post epost ⊑ wp (x.liftM interp) post epost := by
  induction x with
  | pure a => exact WPMonad.pure_le_wp_pure a post epost
  | lift_bind op cont ih =>
    change (spec op).apply (fun b => ((cont b).liftM spec).apply post epost) epost ⊑ _
    apply PartialOrder.rel_trans (hspec op _ _)
    apply PartialOrder.rel_trans (WP.wp_consequence (interp op) _ _ epost ih)
    exact WPMonad.bind_le_wp_bind _ _ _ _

/-- Universal quantification over responses gives precisely structural partial correctness. -/
theorem liftM_forall_iff (x : P.FreeM α) (post : α → Prop) :
    (x.liftM (fun _ => (⟨fun post (_ : PUnit) => ∀ b, post b⟩ :
      PredTrans Prop PUnit _))).apply post ⟨⟩ ↔
        ∀ a, MonadAttach.CanReturn x a → post a := by
  induction x with
  | pure a => simp
  | lift_bind op cont ih =>
    change (∀ b, _) ↔ _
    simp only [pure_bind, ih, canReturn_lift_bind]
    exact ⟨fun h a ⟨b, hb⟩ => h b a hb, fun h b a hb => h a ⟨b, hb⟩⟩

end PFunctor.FreeM
