/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Devon Tuma
-/

module

public import Cslib.Foundations.Data.PFunctor.Free.MonadAttach
public import Cslib.Foundations.Control.Monad.ExactWP
public import Std.WP.Monad.Basic
public import Std.WP.Monad.Sound
public import Std.WP.Conjunctive
public import Std.WP.EStack
public import Std.WP.Triple.Basic

/-!
# Weakest preconditions for polynomial free programs

An operation handler into core's `Lean.Order.PredTrans` extends to a `Std.WP.WPMonad`
interpretation by `FreeM.liftM`. Different readings can be installed locally: structural
correctness, expected cost, and probability bounds share the same program syntax.

The constructions are explicit because the choice of operation semantics is not determined
by the polynomial functor. Inspired by `PolyFun.PFunctor.Free.WP.Upstream`.
-/

@[expose] public section

universe uA uB v w z

namespace PFunctor.FreeM

open Lean.Order Std.WP

variable {P : PFunctor.{uA, uB}} {Pred : Type v} {EPred : Type w} {α : Type uB}

/-- Interpreting operations by monotone predicate transformers preserves monotonicity. -/
theorem monotone_liftM [Lean.Order.PartialOrder Pred] [Lean.Order.PartialOrder EPred]
    (interp : (op : P.A) → PredTrans Pred EPred (P.B op))
    (hinterp : ∀ op, (interp op).monotone) (x : P.FreeM α) :
    (x.liftM interp).monotone := by
  induction x with
  | pure a => exact fun _ _ _ _ _ h => h a
  | lift_bind op cont ih =>
    intro post post' epost epost' hepost hpost
    exact hinterp op _ _ _ _ hepost fun b => ih b _ _ _ _ hepost hpost

/-- The core WP interpretation generated by a monotone operation handler. -/
@[instance_reducible]
def wpMonad [Assertion Pred] [Assertion EPred]
    (interp : (op : P.A) → PredTrans Pred EPred (P.B op))
    (hinterp : ∀ op, (interp op).monotone) : WPMonad P.FreeM Pred EPred where
  toWP _ := ⟨FreeM.liftM interp, monotone_liftM interp hinterp⟩
  pure_le_wp_pure _ _ _ := PartialOrder.rel_refl
  bind_le_wp_bind x f post epost := by
    change (x.liftM interp >>= fun a => (f a).liftM interp).apply post epost ⊑ _
    rw [← liftM_bind]
    exact PartialOrder.rel_refl

instance instExactWPMonad [Assertion Pred] [Assertion EPred]
    (interp : (op : P.A) → PredTrans Pred EPred (P.B op))
    (hinterp : ∀ op, (interp op).monotone) :
    @Cslib.ExactWPMonad P.FreeM Pred EPred _ _ _ (wpMonad interp hinterp) := by
  let : WPMonad P.FreeM Pred EPred := wpMonad interp hinterp
  constructor
  · intro α a post epost
    exact PartialOrder.rel_refl
  · intro α β x f post epost
    change ((x >>= f).liftM interp).apply post epost ⊑ _
    rw [liftM_bind]
    exact PartialOrder.rel_refl

/-- This interpretation is the ordinary monadic fold into `PredTrans`. -/
theorem wpMonad_wp [Assertion Pred] [Assertion EPred]
    (interp : (op : P.A) → PredTrans Pred EPred (P.B op))
    (hinterp : ∀ op, (interp op).monotone) (x : P.FreeM α)
    (post : α → Pred) (epost : EPred) :
    ((wpMonad interp hinterp).toWP α).wp x post epost =
      (x.liftM interp).apply post epost := rfl

/-- Interpret a free program through a handler into a monad with a core WP interpretation. -/
@[instance_reducible]
def wpMonadOfHandler {m : Type uB → Type z} [Monad m]
    [Assertion Pred] [Assertion EPred] [WPMonad m Pred EPred]
    (interp : (op : P.A) → m (P.B op)) : WPMonad P.FreeM Pred EPred where
  toWP _ :=
    { wpTrans x := WP.wpTrans (x.liftM interp)
      wp_trans_monotone x := WP.wp_trans_monotone (x.liftM interp) }
  pure_le_wp_pure a post epost := WPMonad.pure_le_wp_pure a post epost
  bind_le_wp_bind x f post epost := by
    change wp (x.liftM interp) (fun a => wp ((f a).liftM interp) post epost) epost ⊑
      wp ((x >>= f).liftM interp) post epost
    rw [liftM_bind]
    exact WPMonad.bind_le_wp_bind _ _ _ _

instance instExactWPMonadOfHandler {m : Type uB → Type z} [Monad m]
    [Assertion Pred] [Assertion EPred] [WPMonad m Pred EPred]
    [Cslib.ExactWPMonad m Pred EPred] (interp : (op : P.A) → m (P.B op)) :
    @Cslib.ExactWPMonad P.FreeM Pred EPred _ _ _ (wpMonadOfHandler interp) := by
  let : WPMonad P.FreeM Pred EPred := wpMonadOfHandler interp
  constructor
  · intro α a post epost
    exact Cslib.ExactWPMonad.pure_wp_le (m := m) a post epost
  · intro α β x f post epost
    change wp ((x >>= f).liftM interp) post epost ⊑ _
    rw [liftM_bind]
    exact Cslib.ExactWPMonad.wp_bind_le (m := m) _ _ _ _

/-- Per-operation lower bounds extend to a lower bound for the interpreted program. -/
theorem liftM_le_wp {m : Type uB → Type z} [Monad m]
    [Assertion Pred] [Assertion EPred] [WPMonad m Pred EPred]
    (spec : (op : P.A) → PredTrans Pred EPred (P.B op))
    (interp : (op : P.A) → m (P.B op))
    (hspec : ∀ op post epost, (spec op).apply post epost ⊑ wp (interp op) post epost)
    (x : P.FreeM α) (post : α → Pred) (epost : EPred) :
    (x.liftM spec).apply post epost ⊑ wp (x.liftM interp) post epost := by
  induction x with
  | pure a => exact WPMonad.pure_le_wp_pure a post epost
  | lift_bind op cont ih =>
    change (spec op).apply (fun b => ((cont b).liftM spec).apply post epost) epost ⊑ _
    apply PartialOrder.rel_trans (hspec op _ _)
    apply PartialOrder.rel_trans (WP.wp_consequence (interp op) _ _ epost ih)
    exact WPMonad.bind_le_wp_bind _ _ _ _

/-- The postcondition holds for every execution using the chosen response sets.
Install this interpretation locally to use core `vcgen` on native free programs. -/
@[instance_reducible]
def forallWP (responses : (op : P.A) → Set (P.B op)) : WPMonad P.FreeM Prop EStack⟨⟩ :=
  wpMonad (fun op => ⟨fun post _ => ∀ value ∈ responses op, post value⟩)
    (fun _ _ _ _ _ _ h hp value hv => h value (hp value hv))

instance instExactWPMonadForallWP (responses : (op : P.A) → Set (P.B op)) :
    @Cslib.ExactWPMonad P.FreeM Prop EStack⟨⟩ _ _ _ (forallWP responses) :=
  instExactWPMonad _ _

/-- The universal interpretation quantifies over precisely the chosen possible outputs. -/
theorem forallWP_iff (responses : (op : P.A) → Set (P.B op))
    (x : P.FreeM α) (post : α → Prop) :
    ((forallWP responses).toWP α).wp x post () ↔
      ∀ a ∈ x.possibleOutputs responses, post a := by
  change (x.liftM (fun op =>
    (⟨fun post (_ : EStack⟨⟩) => ∀ b ∈ responses op, post b⟩ :
      PredTrans Prop EStack⟨⟩ _))).apply post () ↔ _
  induction x with
  | pure a =>
    change post a ↔ ∀ b, b = a → post b
    simp
  | lift_bind op cont ih =>
    change (∀ b ∈ responses op, _) ↔ _
    simp only [pure_bind, ih, possibleOutputs_lift_bind, Set.mem_iUnion, exists_prop,
      forall_exists_index, and_imp]
    exact ⟨fun h a b hb ha => h b hb a ha, fun h b hb a ha => h a b hb ha⟩

/-- The all-responses interpretation is structural partial correctness. -/
theorem forallWP_univ_iff (x : P.FreeM α) (post : α → Prop) :
    ((forallWP (P := P) (fun _ => Set.univ)).toWP α).wp x post () ↔
      ∀ a, MonadAttach.CanReturn x a → post a :=
  forallWP_iff _ x post

@[spec]
theorem forallWP_lift_spec (responses : (op : P.A) → Set (P.B op))
    (op : P.A) (post : P.B op → Prop) (epost : EStack⟨⟩) :
    letI : WPMonad P.FreeM Prop EStack⟨⟩ := forallWP responses
    ⦃∀ value ∈ responses op, post value⦄ lift op ⦃post; epost⦄ := by
  let : WPMonad P.FreeM Prop EStack⟨⟩ := forallWP responses
  exact ⟨fun h => h⟩

instance instLawfulWPMonadAttachForallWP :
    @LawfulWPMonadAttach P.FreeM Prop EStack⟨⟩ _ _ _ _ _
      (forallWP (P := P) (fun _ => Set.univ)) := by
  let : WPMonad P.FreeM Prop EStack⟨⟩ := forallWP (fun _ => Set.univ)
  refine ⟨fun hcan hwp => ?_⟩
  have h := of_top_le_prop hwp
  simp only [ofProp_prop_eq] at h
  exact (forallWP_univ_iff _ _).mp h _ hcan

/-- A universal interpretation preserves conjunction, for any choice of responses. -/
theorem forallWP_conjunctive (responses : (op : P.A) → Set (P.B op))
    (x : P.FreeM α) :
    letI : WPMonad P.FreeM Prop EStack⟨⟩ := forallWP responses
    WPConjunctive x := by
  let : WPMonad P.FreeM Prop EStack⟨⟩ := forallWP responses
  constructor
  intro Q₁ Q₂ E₁ E₂
  simp only [meet_prop_eq_and]
  intro h
  apply (forallWP_iff responses x _).mpr
  intro a ha
  simp only [meet_apply, meet_prop_eq_and]
  exact ⟨(forallWP_iff responses x Q₁).mp h.1 a ha,
    (forallWP_iff responses x Q₂).mp h.2 a ha⟩

/-- Some execution using the chosen response sets establishes the postcondition. -/
@[instance_reducible]
def existsWP (responses : (op : P.A) → Set (P.B op)) : WPMonad P.FreeM Prop EStack⟨⟩ :=
  wpMonad (fun op => ⟨fun post _ => ∃ value ∈ responses op, post value⟩)
    (fun _ _ _ _ _ _ h ⟨value, hv, hp⟩ => ⟨value, hv, h value hp⟩)

instance instExactWPMonadExistsWP (responses : (op : P.A) → Set (P.B op)) :
    @Cslib.ExactWPMonad P.FreeM Prop EStack⟨⟩ _ _ _ (existsWP responses) :=
  instExactWPMonad _ _

/-- The existential interpretation selects one of the chosen possible outputs. -/
theorem existsWP_iff (responses : (op : P.A) → Set (P.B op))
    (x : P.FreeM α) (post : α → Prop) :
    ((existsWP responses).toWP α).wp x post () ↔
      ∃ a ∈ x.possibleOutputs responses, post a := by
  change (x.liftM (fun op =>
    (⟨fun post (_ : EStack⟨⟩) => ∃ b ∈ responses op, post b⟩ :
      PredTrans Prop EStack⟨⟩ _))).apply post () ↔ _
  induction x with
  | pure a =>
    change post a ↔ ∃ b, b = a ∧ post b
    simp
  | lift_bind op cont ih =>
    change (∃ b ∈ responses op, _) ↔ _
    simp only [pure_bind, ih, possibleOutputs_lift_bind, Set.mem_iUnion, exists_prop]
    exact ⟨fun ⟨b, hb, a, ha, hp⟩ => ⟨a, ⟨b, hb, ha⟩, hp⟩,
      fun ⟨a, ⟨b, hb, ha⟩, hp⟩ => ⟨b, hb, a, ha, hp⟩⟩

@[spec]
theorem existsWP_lift_spec (responses : (op : P.A) → Set (P.B op))
    (op : P.A) (post : P.B op → Prop) (epost : EStack⟨⟩) :
    letI : WPMonad P.FreeM Prop EStack⟨⟩ := existsWP responses
    ⦃∃ value ∈ responses op, post value⦄ lift op ⦃post; epost⦄ := by
  let : WPMonad P.FreeM Prop EStack⟨⟩ := existsWP responses
  exact ⟨fun h => h⟩

end PFunctor.FreeM
